### ISSUE TITLE
3x1 powerwall prefab

### ISSUE THREAD

**Issue by percramer** [livingenvironmentslab/UniCAVE#5]
Hi,

is there a sample or Some info available on how to create a powerwall that is just 3 screens width?

Regards,

Per

**Comment by jamesmoney** [comment]
@percramer There are several prefabs in the project that have something similar. There is a powerwall one and a tri-monitor that could be used as a starting point. (See https://github.com/livingenvironmentslab/UniCAVE/tree/master/UniCAVE2017/Assets/UniCave/Prefabs)

If you need to make one from scratch, take one of the existing prefabs and copy it. Then update the model for the walls. We did this here using blender, but you could use 3ds max as long as Unity can read the output model. Once this is done, you'll have to update the sizes for each wall throughout the scene tree. Then modify the tracking system settings for your environment. Finally, make sure the hostname/machine names are correct. If they are not, certain scripts get dropped since it believes it is running on a slave node.

**Comment by percramer** [comment]
@jamesmoney Sorry i totally missed that folder... i feel stupid now :-) I will do some testing then to see if i can get it up and running (need to download an older version of Unity first because i think it isn't working in the newer ones yet

**Comment by jamesmoney** [comment]
@percramer  It should work fine if you using the 2017 folder. I have it running here on Unity 2018.1 right now. I'm not sure if anyone here has tried the latest 2018 build, but I don't expect it to break anything.
